# Generated by Django 3.0.10 on 2020-09-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pesanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('pesanan', models.TextField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
